"use client";

import * as React from "react";
import { AlertTriangle, Landmark } from "lucide-react";

import { settlementsApi } from "@/frontend/api";
import { useApiQuery, describeApiError } from "@/frontend/hooks/use-api";
import { Button } from "@/frontend/components/ui/button";
import { Badge } from "@/frontend/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/frontend/components/ui/card";
import { Skeleton } from "@/frontend/components/ui/skeleton";
import { EmptyState } from "@/frontend/components/shared/empty-state";
import { RequiresApi } from "./requires-api";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/frontend/components/ui/table";
import { formatMoney } from "@/shared/utils/common.util";

/**
 * What KMC owes this vendor, and what it has already paid.
 *
 * Read-only on purpose. Generating a settlement, approving it and instructing
 * the payout are the authority's decisions and live on their side of the
 * portal; a vendor watching their own money move must be able to see every
 * step without being able to move it. The list is scoped by the API to the
 * caller's own vendor, so there is no filter here and no id to pass.
 */

const STATUS_TONE: Record<string, { label: string; variant: "default" | "secondary" | "outline" }> = {
  DRAFT: { label: "Being prepared", variant: "outline" },
  PENDING_APPROVAL: { label: "With KMC for approval", variant: "secondary" },
  APPROVED: { label: "Approved, awaiting payout", variant: "default" },
  PAID: { label: "Paid", variant: "default" },
  REJECTED: { label: "Sent back", variant: "outline" },
};

function VendorSettlementsViewInner() {
  const query = useApiQuery(["vendor", "settlements"], () =>
    settlementsApi.list({ pageSize: 50 }).then((r) => r.data),
  );

  if (query.isLoading) return <Skeleton className="h-64 w-full rounded-xl" />;

  if (query.isError) {
    return (
      <EmptyState
        icon={AlertTriangle}
        title="Could not load your settlements"
        description={describeApiError(query.error)}
        action={
          <Button variant="outline" size="sm" onClick={() => void query.refetch()}>
            Try again
          </Button>
        }
      />
    );
  }

  const rows = query.data ?? [];

  if (rows.length === 0) {
    return (
      <EmptyState
        icon={Landmark}
        title="No settlements yet"
        description={
          "A settlement is generated by KMC for a period of trading once that period closes. " +
          "Nothing is missing — there simply has not been one yet."
        }
      />
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">Your settlements</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Period</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">Collected</TableHead>
                <TableHead className="text-right">KMC commission</TableHead>
                <TableHead className="text-right">Your share</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {rows.map((s) => {
                const tone = STATUS_TONE[s.status] ?? { label: s.status, variant: "outline" as const };
                return (
                  <TableRow key={s.id}>
                    <TableCell className="whitespace-nowrap">
                      {new Date(s.periodStart).toLocaleDateString("en-IN", {
                        day: "2-digit",
                        month: "short",
                      })}
                      {" – "}
                      {new Date(s.periodEnd).toLocaleDateString("en-IN", {
                        day: "2-digit",
                        month: "short",
                        year: "numeric",
                      })}
                    </TableCell>
                    <TableCell>
                      <Badge variant={tone.variant}>{tone.label}</Badge>
                    </TableCell>
                    <TableCell className="text-right tabular-nums">
                      {formatMoney(s.grossCollected)}
                    </TableCell>
                    <TableCell className="text-right tabular-nums text-muted-foreground">
                      − {formatMoney(s.commissionAmount)}
                    </TableCell>
                    <TableCell className="text-right font-semibold tabular-nums">
                      {formatMoney(s.vendorShare)}
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        </div>
      </CardContent>
    </Card>
  );
}

/**
 * Nothing here renders without a backend. See `RequiresApi` for why this screen
 * does not fall back to the demo dataset the rest of the portal uses.
 */
export function VendorSettlementsView() {
  return (
    <RequiresApi>
      <VendorSettlementsViewInner />
    </RequiresApi>
  );
}
